<a href="https://colab.research.google.com/github/mj00714/deep-learning-challenge/blob/main/AlphabetSoupCharity_Optimization_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Optimization attempt #2 - changing the activation mode of the model

In [137]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [138]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [139]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [140]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [141]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
threshold = 100
value_counts = application_df['APPLICATION_TYPE'].value_counts()
application_types_to_replace = value_counts[value_counts < threshold].index.to_list()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: APPLICATION_TYPE, dtype: int64

In [142]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [143]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_value_counts = application_df['CLASSIFICATION'].value_counts()
class_value_counts_greater_than_one = class_value_counts[class_value_counts > 1]
class_value_counts_greater_than_one.head(25)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
Name: CLASSIFICATION, dtype: int64

In [144]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
class_threshold = 15
class_value_counts = application_df['CLASSIFICATION'].value_counts()
classifications_to_replace = class_value_counts[class_value_counts < class_threshold].index.to_list()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
Other      143
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C2300       32
C7200       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
Name: CLASSIFICATION, dtype: int64

In [145]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies_df = pd.get_dummies(application_df)
application_dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [146]:
# Split our preprocessed data into our features and target arrays
y = application_dummies_df['IS_SUCCESSFUL']
X = application_dummies_df.drop(['IS_SUCCESSFUL'], axis=1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [147]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [148]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train.columns)
hidden_nodes_layer1 =  120
hidden_nodes_layer2 = 50

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="tanh"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_30 (Dense)            (None, 120)               7800

 dense_31 (Dense)            (None, 50)                6050

 dense_32 (Dense)            (None, 1)                 51

=================================================================
Total params: 13901 (54.30 KB)
Trainable params: 13901 (54.30 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [149]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [150]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5753 - accuracy: 0.7190
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5586 - accuracy: 0.7302
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5533 - accuracy: 0.7306
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7312
Epoch 5/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5482 - accuracy: 0.7328
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7331
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7329
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7351
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7350
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7360
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7358
Epoch 12/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5394 - accuracy: 0.7385
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7371
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7370
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7372
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7372
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7378
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7390
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7390
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7392
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7395
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7401
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7388
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7405
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7399
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5326 - accuracy: 0.7407
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7414
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7406
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5316 - accuracy: 0.7417
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7414
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5310 - accuracy: 0.7413
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7412
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5308 - accuracy: 0.7413
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5300 - accuracy: 0.7419
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7421
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7413
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7413
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7422
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7427
Epoch 40/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5289 - accuracy: 0.7419
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5289 - accuracy: 0.7423
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5286 - accuracy: 0.7424
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7423
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5284 - accuracy: 0.7423
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5282 - accuracy: 0.7425
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5278 - accuracy: 0.7431
Epoch 47/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5276 - accuracy: 0.7436
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5275 - accuracy: 0.7428
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5276 - accuracy: 0.7434
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5273 - accuracy: 0.7432
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5271 - accuracy: 0.7429
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5273 - accuracy: 0.7435
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5268 - accuracy: 0.7440
Epoch 54/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5269 - accuracy: 0.7436
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5268 - accuracy: 0.7445
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5267 - accuracy: 0.7440
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5266 - accuracy: 0.7439
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5263 - accuracy: 0.7431
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5264 - accuracy: 0.7435
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5260 - accuracy: 0.7438
Epoch 61/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5258 - accuracy: 0.7445
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5261 - accuracy: 0.7437
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5257 - accuracy: 0.7431
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5260 - accuracy: 0.7444
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5256 - accuracy: 0.7434
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5260 - accuracy: 0.7432
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5255 - accuracy: 0.7441
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5254 - accuracy: 0.7441
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5253 - accuracy: 0.7445
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5253 - accuracy: 0.7449
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5250 - accuracy: 0.7441
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5250 - accuracy: 0.7453
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5250 - accuracy: 0.7446
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7446
Epoch 75/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5248 - accuracy: 0.7448
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5247 - accuracy: 0.7439
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5249 - accuracy: 0.7449
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7451
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5243 - accuracy: 0.7453
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5245 - accuracy: 0.7446
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5244 - accuracy: 0.7452
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5242 - accuracy: 0.7444
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5244 - accuracy: 0.7448
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5240 - accuracy: 0.7451
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5241 - accuracy: 0.7442
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5240 - accuracy: 0.7445
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5240 - accuracy: 0.7446
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5238 - accuracy: 0.7447
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5241 - accuracy: 0.7452
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5236 - accuracy: 0.7443
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5237 - accuracy: 0.7449
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5236 - accuracy: 0.7450
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5237 - accuracy: 0.7448
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5237 - accuracy: 0.7447
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5233 - accuracy: 0.7447
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5233 - accuracy: 0.7447
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5233 - accuracy: 0.7449
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5233 - accuracy: 0.7458
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5234 - accuracy: 0.7448
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5233 - accuracy: 0.7447

In [151]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5625 - accuracy: 0.7257 - 470ms/epoch - 2ms/step
Loss: 0.5625448822975159, Accuracy: 0.7257142663002014

In [152]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(